// src/fontAwesomeConfig.ts
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAppleAlt,
  faBreadSlice,
  faCarrot,
  faCheese,
  faEgg,
  faFish,
  faLemon,
  faPepperHot,
  faBacon,
  faIceCream,
  faPizzaSlice,
  faCoffee,
  faSeedling,
  faDrumstickBite,
  faWineBottle,
  faGlassMartiniAlt,
  faBeer,
  faCookie,
  faCandyCane,
  faMugHot,
  faBirthdayCake,
  faHamburger,
  faHotdog,
  faLeaf,
  faWineGlassAlt,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faAppleAlt,
  faBreadSlice,
  faCarrot,
  faCheese,
  faEgg,
  faFish,
  faLemon,
  faPepperHot,
  faBacon,
  faIceCream,
  faPizzaSlice,
  faCoffee,
  faSeedling,
  faDrumstickBite,
  faWineBottle,
  faGlassMartiniAlt,
  faBeer,
  faCookie,
  faCandyCane,
  faMugHot,
  faBirthdayCake,
  faHamburger,
  faHotdog,
  faLeaf,
  faWineGlassAlt
);
